### ISSUE TITLE
Only one of two PV installation shown (both present on one address)

### ISSUE THREAD

**Issue by kuuf1986** [fsaris/home-assistant-zonneplan-one#99] opened 2024-03-06 09:35 UTC
hi,

I have 2 separate Zonneplan PV installations. One with 15 panels (installed in 2021) and one with 18 panels (installed in 2024). The integration only shows one of the installations. Some sensors are duplicated ('Zonneplan last measured value' / 'Zonneplan yield total') but the given values belong only to the first installation of 2021. The sensor Zonneplan yield today shows the combined value of both PV installations. 

![image](https://github.com/fsaris/home-assistant-zonneplan-one/assets/18405177/2ceb9f0d-6ab3-4361-8199-67d929aa3d1a)

Debug log;
The log shows both installations and unique 'last_measured_power_value' numbers. 

> [{'uuid': '<UUID1>', 'label': 'PV Installatie', 'type': 'pv_installation', 'start_date': '2021-06-24T22:00:00.000000Z', 'end_date': '2031-06-24T22:00:00.000000Z', 'meta': {'identifier': '**Identifier of installation 1**', 'name': 'Zonneplan One omvormer', 'panel_count': **15**, 'panel_type': None, 'installation_wp': 5550, 'panel_wp': 370, 'first_measured_at': '2021-06-24T18:31:23.000000Z', 'last_measured_at': '2024-03-06T08:55:23.000000Z', 'last_measured_power_value': **2281**, 'grid_stabilization_active': False, 'total_power_measured': 13074780, 'network': {'name': 'Onbekend', 'color': 'unknown', 'status': 'Onbekend'}, 'sgn_serial_number': '<serial nmbr>', 'module_firmware_version': 'v3.0.10', 'inverter_firmware_version': 'v3.036', 'show_in_contract_screen': False, 'enable_pv_analysis': False}}, {'uuid': '<UUID2>', 'label': 'PV Installatie', 'type': 'pv_installation', 'start_date': None, 'end_date': None, 'meta': {'identifier': '**Identifier of installation 2**', 'name': 'Zonneplan One omvormer', 'panel_count': **18**, 'panel_type': None, 'installation_wp': 7920, 'panel_wp': 440, 'first_measured_at': '2024-03-05T15:10:09.000000Z', 'last_measured_at': '2024-03-06T08:55:00.000000Z', 'last_measured_power_value': **2819**, 'grid_stabilization_active': False, 'total_power_measured': 5900, 'network': {'name': 'Vodafone', 'color': 'poor', 'status': 'Slecht'}, 'sgn_serial_number': '<serial nmbr>', 'module_firmware_version': '1.2.1r', 'inverter_firmware_version': '3063', 'show_in_contract_screen': False, 'enable_pv_analysis': False}}], 'features': [], 'buttons': []}]

I removed the integration from Homeassistant and deleted it from HACS. Installed again via HACS. Rebooted and installed the integration again but this didn't resolve my issue.

I hope you can help out!

Thanks in advance!

Best regards, Ruud

**Comment by fsaris** [comment] 2024-03-06 19:03
Looks like 2 different installs. 1 with 15 panels and 1 with 18 panels.

Was your install changed from 15 to 18 panels?

**Comment by kuuf1986** [comment] 2024-03-06 19:37
I have two separate installations. So also two converters. 1 with 15 panels and 1 with 18 panels. Total 33 panels.

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by fsaris** [comment] 2024-03-07 06:17
Ah, sorry misread your first comment.

Need to investigate this further. This worked before but I suspect that the last changes broke this

**Comment by fsaris** [comment] 2024-03-08 06:18
Can you provide some logs with debug data? That enables me to reproduce the situation in my test setup. You can send it to me for example using direct message on the forum https://community.home-assistant.io/u/minifranske/

**Comment by fsaris** [comment] 2024-03-08 19:11
Are you able to view the statistics of each install separately in the Zonneplan app?

**Comment by fsaris** [comment] 2024-03-08 22:37
Can you test version 2024.3.0b2

Each install gets its own device and the total yield is now part of a different device that holds all total values

**Comment by kuuf1986** [comment] 2024-03-09 07:36
> Are you able to view the statistics of each install separately in the Zonneplan app?

per PV installation I can see the momentary delivered power and the total delivered power of the installation. the grahps only show thet combined power

**Comment by fsaris** [comment] 2024-03-09 12:21
ah, sorry. tagged the wrong branch. Please try [2024.3.0b3](https://github.com/fsaris/home-assistant-zonneplan-one/releases/tag/2024.3.0b3)

**Comment by kuuf1986** [comment] 2024-03-09 14:38
I get this now:
Two devices:
![image](https://github.com/fsaris/home-assistant-zonneplan-one/assets/18405177/53d8dac5-d17c-4606-853f-c5aa5ea114c6)

First one:
![image](https://github.com/fsaris/home-assistant-zonneplan-one/assets/18405177/177d050c-18cc-4568-aadc-55b725dd8dae)

Second one:
![image](https://github.com/fsaris/home-assistant-zonneplan-one/assets/18405177/fbc913dc-fbcf-4695-ba00-8d86192c25f7)

The second one shows now two unique last measured values which match both installations so this is good. 
One remark; the device info mentions "Zonneplan One omvormer 18 panels door Zonneplan". While the sensors behind this device belong to both installations. So perhaps leave out the 18 panels in the name?

For the rest does this solve the issue I've initiated. I can read both installations now so that is already very nice! :) Thanks!

**Comment by fsaris** [comment] 2024-03-09 15:57
Can you try to remove the integration and re-add it again? You should now have 3 devices.
1. Zonneplan (totals)
2. Zonneplan pv 1
3. Zonneplan pv 2

Currently your PV installs are still combined 

When that doesn't resolve the issue can you provide a dump of your logs with debug enabled for Zonneplan?

**Comment by kuuf1986** [comment] 2024-03-10 08:08
Reinstall did indeed create three devices, exactly as you indicated. Seems to work just fine now! Thanks!

**Comment by fsaris** [comment] 2024-03-17 10:20
Fix is released with [2024.3.0](https://github.com/fsaris/home-assistant-zonneplan-one/releases/tag/2024.3.0)

**Closed by fsaris** 2024-03-17 10:20 UTC
