### ISSUE TITLE
Show electricity costs today and gas costs today in entity

### ISSUE THREAD

**Issue by CSC9110** [fsaris/home-assistant-zonneplan-one#67] opened 2023-05-21 17:34 UTC
Is it possible to display Electricity costs today and Gas costs today in an additional entity?

This has been added to the Zonneplan app since last week.

**Comment by CrazyHenk44** [comment] 2023-07-01 19:51
I see a 

zonneplan_p1_electricity_consumption_today_cost and one for gas, but the value seem seem to be 'unavailable' for both.

**Comment by fsaris** [comment] 2023-11-18 10:26
Can you enable debug logging and check if the value is present in the data? (to enable debug logging see https://github.com/fsaris/home-assistant-zonneplan-one#troubleshooting)

I don't have a energy contract so also don't get these values

**Comment by CrazyHenk44** [comment] 2023-11-18 16:39
I don't see anything monetary in the debug output. It's all about usage and tariffs, but nowhere is a mention of the costs today/this month/this year or anything.

**Comment by fschaal** [comment] 2023-11-24 06:46
For me im not seeing this sensor. Am I missing something?

**Comment by fsaris** [comment] 2023-11-24 07:51
It's currently not yet in a official version. You need to install the main branch

**Comment by martijnrusschen** [comment] 2023-11-25 14:30
When are you planning to release this? I’d love to capture this data in a sensor.

**Comment by martijnrusschen** [comment] 2023-11-29 19:31
According to https://github.com/fsaris/home-assistant-zonneplan-one/compare/main...0.0.21 all code from the main branch is in the latest release. I've installed that version, but I can't find the sensor. Has anyone been able to get this sensor to work using the main branch? I've also looked at the debug logs but can't find a mention of the data mentioned.

**Comment by fsaris** [comment] 2023-11-29 19:53
ah, sorry. The sensor that was added is a different one (gas price tomorrow).

If you can point to the value in the debug data that should be turned into a sensor that would be helpful. 
I don't have a energy contract so these values are not available to me.

Enable debugging https://github.com/fsaris/home-assistant-zonneplan-one#troubleshooting and try to find a value in the logs you can match with the value in the app.

**Comment by martijnrusschen** [comment] 2023-11-29 20:24
Thanks for confirming, I thought I was going crazy :) 

I'll take a closer look at the debug output tomorrow, I wasn't able to find anything related to cost yet. Just usage and tariffs so far.

**Comment by fsaris** [comment] 2023-12-05 19:40
@martijnrusschen please test https://github.com/fsaris/home-assistant-zonneplan-one/releases/tag/0.0.22b3 :)

should have the values (sensors are disabled by default). Could be that the shown value should be formatted differently.

if value stays 0 then please check the debug logs for values

**Comment by martijnrusschen** [comment] 2023-12-05 19:50
Amazing! I installed the beta version and can confirm the sensors are showing up. I don't have a gas contract, so I enabled the electricity sensors only. 

Electricity delivery cost: 
![Screenshot 2023-12-05 at 20 46 48@2x](https://github.com/fsaris/home-assistant-zonneplan-one/assets/1412392/cc6ee272-adf3-4f07-bd6a-c3bcff3bc653)

This could probably be rounded to 2 decimals. 

Electricity produced cost:
![Screenshot 2023-12-05 at 20 49 55@2x](https://github.com/fsaris/home-assistant-zonneplan-one/assets/1412392/7da37b2f-f60f-4410-ac32-9f677e4b62ca)

It looks like I didn't produce energy today, which is correct assuming that's the reason it's unknown. I'll keep an eye on this tomorrow to see if it changes.

**Comment by CrazyHenk44** [comment] 2023-12-05 20:53
In beta 3 I can confirm the costs are now visible in HA.

![Safari Thuis — Overzicht – Home Assistant 21 51 46@2x](https://github.com/fsaris/home-assistant-zonneplan-one/assets/5298235/5df38035-3a7b-4f29-8034-af5823b2f9b0)

**Comment by fsaris** [comment] 2023-12-06 06:46
@martijnrusschen @CrazyHenk44 are the amounts equal to what is shown in the Zonneplan APP (no additional multiply or divide by 10 needed)?

**Comment by CrazyHenk44** [comment] 2023-12-06 06:51
They are correct as is and match the Zonneplan app.

**Comment by fsaris** [comment] 2023-12-07 18:54
Released with [0.0.22](https://github.com/fsaris/home-assistant-zonneplan-one/releases/tag/0.0.22)

**Closed by fsaris** 2023-12-07 18:54 UTC
Labels: enhancement
