### ISSUE TITLE
deprecated alias

### ISSUE THREAD

**Issue by freddy357** [fsaris/home-assistant-zonneplan-one#116] opened 2024-05-13 17:36 UTC
Logger: homeassistant.helpers.typing
Source: helpers/deprecation.py:206
First occurred: May 11, 2024 at 08:59:09 (4 occurrences)
Last logged: May 11, 2024 at 08:59:11

HomeAssistantType was used from zonneplan_one, this is a deprecated alias which will be removed in HA Core 2025.5. Use homeassistant.core.HomeAssistant instead, please report it to the author of the 'zonneplan_one' custom integration

**Comment by fsaris** [comment] 2024-05-13 19:25
Duplicate of  #114

Will be part of next release

**Closed by fsaris** 2024-05-13 19:25 UTC
